server:
  port: 7020
logging:
  config: classpath:logback.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor-talin
      port: 6010
      logretentiondays: -1
      ip: 192.168.2.120
    admin:
      addresses: http://192.168.2.120:8080/xxl-job-admin
    accessToken: